# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160925_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midias',
            name='link',
        ),
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 4, 46, 109492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 4, 46, 106417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 4, 46, 107254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 4, 46, 110154, tzinfo=utc)),
        ),
    ]
