# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161023_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='midias',
            name='link',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 5, 59, 979840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 5, 59, 976767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 5, 59, 977529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 5, 59, 980490, tzinfo=utc)),
        ),
    ]
