# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161023_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 29, 5, 874637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 29, 5, 871564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 29, 5, 872333, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 22, 29, 5, 875311, tzinfo=utc)),
        ),
    ]
