# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161024_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='entity',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 21, 21, 33, 512014, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 21, 21, 33, 509306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 21, 21, 33, 510309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 21, 21, 33, 512835, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
