# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161109_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 23, 57, 49, 115219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 23, 57, 49, 112071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media/entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 23, 57, 49, 113338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 23, 57, 49, 116023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='midias',
            name='file',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media/cars'),
        ),
    ]
