# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_markdown.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161109_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_markdown.models.MarkdownField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 0, 35, 56, 499647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 0, 35, 56, 496497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 0, 35, 56, 497736, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 0, 35, 56, 500488, tzinfo=utc)),
        ),
    ]
