# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161110_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='manual',
            field=models.FileField(null=True, upload_to='entity'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 22, 59, 30, 446739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 22, 59, 30, 442552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 22, 59, 30, 444671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 22, 59, 30, 447636, tzinfo=utc)),
        ),
    ]
